### ISSUE TITLE
Line 285 of picohttpparser.c should use ALIGNED macro

### ISSUE THREAD

**Issue by samkho** [h2o/picohttpparser#30]
Line 285 of picohttpparser.c uses gcc aligned attribute directly:

`static const char ranges1[] __attribute__((aligned(16))) = "\x00 "  /* control chars and up to SP */`

This causes problems for MSVC.  There already is an ALIGNED macro that is used elsewhere.  Please use it here as well:

`static const char ALIGNED(16) ranges1[] = "\x00 "  /* control chars and up to SP */`

**Comment by kazuho** [comment]
Thank you for reporting the issue! Fixed in the above commit.
