### ISSUE TITLE
output of phr_decode_chunked ?

### ISSUE THREAD

**Issue by bharatkrishna** [h2o/picohttpparser#34]
I am calling phr_decode_chunked() as shown in the documentation. If I print the buffer, I see chunk lengths too. If I make the same request with curl binary, it outputs a single body with all the chunks stitched together. 

For example here is the output of the buffer. The ones in bold are the chunk sizes I suppose. (This is a bit messy to read since on the server I am just serving data which is all numbers)

**00000005**
3445 
**00000005**
3444 
**0000000A**
3443 3442 
**00000005**
3441 
**0000011D**
3440 3439 3438 3437 3436 3435 3434 3433 3432 3431 3430 3429 3428 3427 3426 3425 3424 3423 3422 3421 3420 3419 3418 3417 3416 3415 3414 3413 3412 3411 3410 3409 3408 3407 3406 3405 3404 3403 3402 3401 3400 3399 3398 3397 3396 3395 3394 3393 3392 3391 3390 3389 3388 3387 3386 3385 3384 
**00000005**
3383 
**00000069**
3382 3381 3380 3379 3378 3377 3376 3375 3374 3373 3372 3371 3370 3369 3368 3367 3366 3365 3364 3363 3362 
**00000005**
3361 
**00000037**
3360 3359 3358 3357 3356 3355 3354 3353 3352 3351 3350 
**00000005**
3349 

---
I wish there was a full working example in C on how to use this library..

**Comment by bharatkrishna** [comment]
A rough flow of my program(in pseudo C code):

```
rv = read(sock, buf, 4096);
phr_parse_response(...); /* I check the headers after this and set chunked_response = 1 if headers indicate */
if (chunked_response) {
    size = rv /* setting this to offset buffer with what has been read so far */
    do {
        while ((rret = read(sock, buf + size, capacity - size)) == -1 && errno == EINTR)
            ;
        if (rret <= 0)
            return IOError;
        /* decode */
        rsize = rret;
        pret = phr_decode_chunked(&decoder, buf + size, &rsize);
        if (pret == -1)
            return ParseError;
        size += rsize;
    } while (pret == -2);
}
printf("%s", buffer);

```

**Comment by Asmod4n** [comment]
The bufsz argument holds the actual length of what was decoded.
You have to limit printf by that size.

**Comment by bharatkrishna** [comment]
I am adding `rsize` of each decode to `size`. So I should limit it by `size` to print the whole buffer?

**Comment by Asmod4n** [comment]
I would guess so, yes.
Where i am using it i simply cut off the buffer each time i use phr_decode_chunked.

**Comment by bharatkrishna** [comment]
Thanks. When I limit the printf by the `size`, it prints the decoded chunks correctly.
