### ISSUE TITLE
Unnecessary bounds check in parse_http_version?

### ISSUE THREAD

**Issue by vinniefalco** [h2o/picohttpparser#35]
It seems this conditional is unnecessary:
https://github.com/h2o/picohttpparser/blob/2a16b2365ba30b13c218d15ed9991576358a6337/picohttpparser.c#L254

Rationale:

We've already located the final CRLFCRLF sequence in the buffer. If `parse_http_version` encounters those characters the `EXPECT_CHAR_NO_CHECK` tests will fail, avoiding iterating past the end of the buffer.

**Comment by kazuho** [comment]
> We've already located the final CRLFCRLF sequence in the buffer.

No. `is_complete` is called only when `last_len` is a non-zero value.
