### ISSUE TITLE
What last_len actually means?

### ISSUE THREAD

**Issue by Gymmasssorla** [h2o/picohttpparser#54]
The signature of `phr_parse_response` is:
```c
/* ditto */
int phr_parse_response(const char *_buf, size_t len, int *minor_version, int *status, const char **msg, size_t *msg_len,
struct phr_header *headers, size_t *num_headers, size_t last_len);
```

How should I provide `last_len` here? For what `last_len` is?

**Comment by Asmod4n** [comment]
last_len is there in case you don't have a complete set of HTTP Headers inside your buffer.
Start off with it being 0 and then in case phr_parse_response returns -2 set it to the length of the buffer you supplied and try it again after you have appended more data to your buffer until phr_parse_response returns a positive number.

**Comment by Gymmasssorla** [comment]
Thank you
