### ISSUE TITLE
`phr_parse_request()` partial parsing doesn't seem to work

### ISSUE THREAD

**Issue by maxvu** [h2o/picohttpparser#76]
When given a buffer generously-sized enough so as to contain all of both the status line and headers (as the example in the readme does), `phr_parse_request()` behaves as advertised and beautifully. But in all other cases, it seems to fail consistently.

In the example code below, I simulate socket communication by introducing a cut and separating the parsing into two calls. It seems that all values of `cur` except for `strlen( req )` return `-1`.

```
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include "picohttpparser.h"

typedef struct phr_header phr_header;

const char * req =
    "POST /file HTTP/1.1\r\n"
    "Host: localhost:8022\r\n"
    "User-Agent: curl/x\r\n"
    "Accept: */*\r\n"
    "Content-Type: application/json\r\n"
    "Content-Length: 9\r\n\r\n"
    "{\"one\":1}";

phr_header   hdr[ 40 ];
size_t       hdrlen;
const char * mtd;
size_t       mtdlen;
const char * pth;
size_t       pthlen;
int          vzn;
int          rc;
int          cut;


int main ( int argc, char ** argv ) {
    cut = 50;
    hdrlen = sizeof( hdr ) / sizeof( hdr[ 0 ] );

    rc = phr_parse_request( req, cut,
        &mtd, &mtdlen, &pth, &pthlen,
        &vzn, hdr, &hdrlen, 0 );

    if ( rc > 0 ) {
        printf( "parse ok\n" );
        exit( 0 );
    } else if ( rc == -1 ) {
        printf( "parse error\n" );
        exit( 1 );
    }

    rc = phr_parse_request( req, strlen( req ),
        &mtd, &mtdlen, &pth, &pthlen,
        &vzn, hdr, &hdrlen, cut );

    if ( rc > 0 ) {
        printf( "parse ok\n" );
    } else if ( rc == -1 ) {
        printf( "parse error\n" );
    } else {
        printf( "parse incomplete\n" );
    }

    return 0;
}
```

Am I misunderstanding the interface? What is the purpose of the last argument and `-2` return, if not for resuming parsing mid-message?

I'm on `master` ([066d2b1](https://github.com/h2o/picohttpparser/commit/066d2b1e9ab820703db0837a7255d92d30f0c9f5)).

**Comment by kazuho** [comment]
Thank you for using picohttpparser.

I think before making the second call to `phr_parse_request`,`mtdlen` has to be *re*initialized to `sizeof(hdr) / sizeof(hdr[0])`.

**Comment by maxvu** [comment]
Excellent - that seems to work!

Thank you for your work and taking the time.
